debug: true
server:
  port: 2020
  servlet:
    context-path: /spring-ai-advance-project

logging:
  level:
    root: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  batch:
    job:
      enabled: false
  http:
    client:
      factory: simple
  main:
    allow-bean-definition-overriding: true
  ai:
    models:
      embedding:
        enabled: true
        default-provider: ollama
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 3030
        collection-name: word_docs_collection
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
      chat:
        options:
          model: phi3:latest

# spring.ai.ollama.init.pull-model-strategy=when_missing # This will pull the model only if it's not already present